version: '3.7'

services:
  rtp-exporter:
    build:
      context: .
    network_mode: host
    command:
      - /rtpexporter.py
      - --interface=wlp3s0
      - --rtp-port-min=100
  prometheus:
    network_mode: "host"
    image: prom/prometheus:v3.0.1
    command:
      - --config.file=/config/prometheus.yml
    volumes:
      - ./config:/config:ro
